### ISSUE TITLE
The "upstream" atlassian agent got DMCA on their GitTea repo

### ISSUE THREAD

**Issue by voarsh2** [haxqer/confluence#11]
The upstream repo for the Atlassian Agent library had their repo removed. This was a couple of months ago  - I haven't checked recently if they re-uploaded their repository somewhere else...

If you don't get a new version of the agent then Atlassian might fix and break the agent..........?

**Comment by haxqer** [comment]
I think AHT will focus on the cloud version, including many new plug-in functions that also support the cloud version.
Because in addition to the cloud version, other versions (server or data center) will be cracked even if the encryption algorithm is complex, so there is no need to waste energy on other versions of encryption algorithm.

There is no need to worry about this problem. Even if you worry about something, you can use the old version. The current version of Server Or Data Center is locally verified, and the old version is feasible. The functions of the old version are sufficient.

**Comment by voarsh2** [comment]
> There is no need to worry about this problem. Even if you worry about something, you can use the old version. The current version of Server Or Data Center is locally verified, and the old version is feasible. The functions of the old version are sufficient.

I suppose - but I personally like up-to-date software, especially since some people won't just be running it localhost... I know  Atlassian's focus is their damn cloud, and they purposefully withhold active feature development on Server/Data Center to entice Cloud.... here's hoping the original maintainer comes back in future - if the keygen breaks.... :D

**Comment by haxqer** [comment]
`Locally verified` means no network authentication is required. I use the wrong words. It should be `offline verification`.
 In addition to the cloud version, all others are `offline verification`.
As long as it is `offline verification` , it can always be cracked.
